apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
metadata:
  name: {{ template "etcd.fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "etcd.name" . }}
spec:
  type: {{ .Values.serviceType }}
  ports:
  - port: {{ .Values.peerPort }}
    name: etcd-server
  - port: {{ .Values.clientPort }}
    name: etcd-client
    {{- if (and (eq .Values.serviceType "NodePort") (not (empty .Values.service.nodePorts.etcdClient)))}}
    nodePort: {{ .Values.service.nodePorts.etcdClient }} 
    {{- end }}
  clusterIP: None
  selector:
    app: {{ template "etcd.name" . }}
    release: {{ .Release.Name | quote }}
