apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: multi-cluster-dns-viewer
  namespace: mc-dns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: multi-cluster-dns
subjects:
- kind: ServiceAccount
  name: multi-cluster-dns
  namespace: mc-dns
