apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: multi-cluster-dns
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","watch","list"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list","get","watch"]
- apiGroups: ["multiclusterdns.kubefed.k8s.io"]
  resources: ["DNSEndpoint","dnsendpoints","dnsendpoints/status"]
  verbs: ["get","watch","list","update"]

