apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-cluster-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: multi-cluster-dns
  template:
    metadata:
      labels:
        app: multi-cluster-dns
    spec:
      serviceAccountName: multi-cluster-dns
      containers:
      - name: multi-cluster-dns
        image: cevalogistics/external-dns:0.5.7.35
        imagePullPolicy: Always
        args:
        - --source=service
        - --source=ingress
        - --publish-internal-services
        - --provider=coredns
        - --log-level={{ .Values.logLevel }}
        - --registry=txt
        - --txt-owner-id={{ .Values.ownerId }}
        env:
        - name: ETCD_URLS
          value: {{ .Values.etcdURL }}
        - name: COREDNS_ONPREM_ADDRESS_SUPPORT
          value: "{{ .Values.CoreDNSOnPremAddressSupport }}"

